version: '3.9'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - \prometheus.yaml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
  zipkins:
    image: openzipkin/zipkin:latest
    container_name: zipkins
    ports:
      - 9411:9411
  
  authorService:
    image: feezankhattak2208/authorsvc:1.0
    container_name: authorService
    ports:
      - 7071:7071
    environment:
      - SERVER_PORT=7071
      - SPRING_APPLICATION_NAME=AuthorService
      - SPRING_ZIPKIN_BASE_URL=http://host.docker.internal:9411/

  bookService:
    image: feezankhattak2208/booksvc:1.0
    container_name: BookService
    ports:
      - 7070:7070
    environment:
      - SERVER_PORT=7070
      - SPRING_APPLICATION_NAME=BookInfoApplicationService
      - SPRING_ZIPKIN_BASE_URL=http://host.docker.internal:9411/
      - AUTHOR_GET_ALL_AUTHOR=http://host.docker.internal:7071/authors
      - AUTHORS_GET_AUTHOR_BY_ID=http://host.docker.internal:7071/authors/author/id/
      - AUTHOR_GET_AUTHOR_BY_NAME=http://host.docker.internal:7071/authors/author/name/

